{
 "title": "billing-api",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Triage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Triage",
   "type": "jdbranham-diagram-panel",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "content": "graph LR\n\nIngress[Ingress] -->|Route to | API{Billing API}\nAPI --> Commands\nAPI --> Queries\nCommands -->|Write| WM[Write Model DB]\nCommands -->|Publish| RMQ[RabbitMQ Exchange] \nRMQ -->|topic| Queue[Event Queues]\nWorker(API Workers) --> |Write| RM(Read Model DB)\nWorker --> |Consumes|Queue\nQueries --> |Read| RM\n",
   "targets": [
    {
     "expr": "billing:traffic:apdex_global_5m",
     "legendFormat": "API"
    },
    {
     "expr": "billing:transactions:success:sum_increase_5m/(billing:transactions:success:sum_increase_5m + billing:transactions:error:sum_increase_5m)",
     "legendFormat": "Commands"
    },
    {
     "expr": "billing:traffic:apdex_by_method_path_5m{path=\"/transaction/:uuid\"}",
     "legendFormat": "Queries"
    },
    {
     "expr": "sum(increase(events_worker_duration_seconds_count[5m]))",
     "legendFormat": "Worker"
    },
    {
     "expr": "sum(increase(event_published_count[5m]))",
     "legendFormat": "RMQ"
    },
    {
     "expr": "sum(increase(event_store_postgres_write_duration_seconds_count[5m]))",
     "legendFormat": "WM"
    },
    {
     "expr": "1-rabbitmq_queue_messages_ready{queue=\"events\"}",
     "legendFormat": "Queue"
    }
   ]
  },
  { "title": "[Business] Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Transactions Created | Conflict | Error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "billing:transactions:success:sum_increase_1m",
     "legendFormat": "Success"
    },
    {
     "expr": "billing:transactions:conflict:sum_increase_1m",
     "legendFormat": "Conflict"
    },
    {
     "expr": "billing:transactions:error:sum_increase_1m",
     "legendFormat": "Error"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Requests per second per 1m",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    { "expr": "billing:traffic:total_rate_1m", "legendFormat": "Traffic" }
   ]
  },
  {
   "title": "Requests per method per 1m",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "billing:traffic:total_rate_by_method_1m",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Requests per path per 1m",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "billing:traffic:total_rate_by_path_1m",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Requests per path per 1m",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "billing:traffic:total_rate_by_path_method_1m",
     "legendFormat": "{{ method }} : {{ path }}"
    }
   ]
  },
  { "title": "Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Healthy Workers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "rabbitmq_queue_consumers{queue=\"events\"}"
    }
   ]
  },
  {
   "title": "[Events Queue] Messages Ready",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 47 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{queue=\"events\"}"
    }
   ]
  },
  {
   "title": "Total connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 47 },
   "targets": [
    { "expr": "rabbitmq_connectionsTotal" }
   ]
  },
  {
   "title": "Queues Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_queue_messages_ready", "legendFormat": "{{ queue }}" }
   ]
  },
  { "title": "Error", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Server Error Rate per 1m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "billing:traffic:server_error_rate_1m",
     "legendFormat": "Server Error rate"
    }
   ]
  },
  {
   "title": "Client Error Rate per 1m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "billing:traffic:client_error_rate_1m",
     "legendFormat": "Client Error rate"
    }
   ]
  },
  { "title": "Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "AVG response times",
   "type": "stat",
   "description": "Max at 0.1s",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "billing:traffic:duration_avg_5m",
     "legendFormat": "Score"
    }
   ]
  },
  {
   "title": "Global Apdex Score",
   "type": "graph",
   "description": "Apdex Score with le at 0.3s and max at 1.5s\n",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "billing:traffic:apdex_global_5m",
     "legendFormat": "Score"
    }
   ]
  },
  {
   "title": "Apdex Score by Path",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "billing:traffic:apdex_by_method_path_5m{path!=\"/monitor/health\"}",
     "legendFormat": "{{ method }} : {{ path }}"
    }
   ]
  },
  {
   "title": "95% SLO",
   "type": "graph",
   "description": "Defined at serve 95% of requests within 300ms\n",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "billing:traffic:95_slo", "legendFormat": "Score" }
   ]
  },
  {
   "title": "AVG response times",
   "type": "bargauge",
   "description": "Max at 0.1s",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "billing:traffic:duration_avg_by_method_path_5m",
     "legendFormat": "{{ method }} : {{ path }}"
    }
   ]
  },
  {
   "title": "Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "billing:traffic:histogram_95_1m",
     "legendFormat": "95"
    },
    {
     "expr": "billing:traffic:histogram_70_1m",
     "legendFormat": "70"
    },
    {
     "expr": "billing:traffic:histogram_50_1m",
     "legendFormat": "50"
    }
   ]
  }
 ]
}